services:
  # user-service için SQL veritabanımız
  postgres:
    image: postgres:16-alpine
    container_name: collabpulse-postgres-new
    environment:
      POSTGRES_DB: collabpulse_user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5499:5432"
    volumes:
      - postgres_new_data:/var/lib/postgresql/data

  # chat-service için NoSQL veritabanımız
  mongo-db:
    image: mongo:7.0
    container_name: collabpulse-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Durum yönetimi ve Heartbeat için Hız Hattımız
  redis-cache:
    image: redis:7.2-alpine
    container_name: collabpulse-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_new_data:
  mongo_data:
  redis_data: