server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        # 1. Kullanıcı Servisi Yönlendirmesi
        - id: user-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter

        # 2. Mesajlaşma/Chat Servisi Yönlendirmesi
        - id: chat-service-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/messages/**, /ws-connect/**
          filters:
            - AuthenticationFilter
  jwt:
    secret: ${JWT_SECRET}